config/routes.rb
EMonies::Application.routes.draw do
  devise_for :people, :controllers => { :registrations => :registrations }
  root :to => 'special#index'

  get 'summary' => 'special#summary'

  resources :people
  resources :purchases
  resources :acceptances

end

app/controllers/purchases_controller.rb
require 'purchases_helper'

class PurchasesController < ApplicationController
  before_action :authenticate_person!

  # GET /purchases
  # GET /purchases.json
  def index
    @purchases = Purchase.includes(:acceptances).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @purchases }
    end
  end

  # GET /purchases/1
  # GET /purchases/1.json
  def show
    @purchase = Purchase.find(params[:id])
    @my_acceptance = @purchase.acceptances.where("person_id = ?", current_person.id)[0]
    if @my_acceptance.nil? then
      @my_acceptance = @purchase.acceptances.new
      @my_acceptance.person = current_person
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @purchase }
    end
  end

  # GET /purchases/new
  # GET /purchases/new.json
  def new
    @purchase = Purchase.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @purchase }
    end
  end

  # GET /purchases/1/edit
  def edit
    @purchase = Purchase.find(params[:id])
  end

  # POST /purchases
  # POST /purchases.json
  def create
    p = purchase_params
    p[:person_id] = current_person.id
    @purchase = Purchase.new(p)

    respond_to do |format|
      if @purchase.save
        PurchasesHelper.recalculate_owes!

        format.html { redirect_to @purchase, notice: 'Purchase was successfully created.' }
        format.json { render json: @purchase, status: :created, location: @purchase }
      else
        format.html { render action: "new" }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /purchases/1
  # PUT /purchases/1.json
  def update
    @purchase = Purchase.find(params[:id])

    respond_to do |format|
      if @purchase.person == current_person && @purchase.update_attributes(purchase_params)
        PurchasesHelper.recalculate_owes!

        format.html { redirect_to @purchase, notice: 'Purchase was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchases/1
  # DELETE /purchases/1.json
  def destroy
    @purchase = Purchase.find(params[:id])

    if @purchase.person == current_person then
      @purchase.destroy
      PurchasesHelper.recalculate_owes!

      respond_to do |format|
        format.html { redirect_to purchases_url }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to purchases_url, :flash => { :error => "Can't delete another users purchases" }}
        format.json { head :no_content }
      end
    end
  end

  private
  def purchase_params
    params.require(:purchase).permit(:name, :amount, :description, :date)
  end
end

app/helpers/purchases_helper.rb
module PurchasesHelper
  # Borrowed from https://stackoverflow.com/questions/9144822/how-to-declare-a-two-dimensional-array-in-ruby.
  # Extended by myself
  class SparseArray
    attr_reader :hash

    def initialize
      @hash = {}
    end

    def [](key)
      hash[key] ||= {}
    end

    def rows
      hash.length
    end

    def merge!(others)
      @hash.merge!(others.hash) do |key, oldval, newval|
        oldval + newval
      end
    end

    def key?(key)
      @hash.key?(key)
    end

    alias_method :length, :rows
  end

  def self.recalculate_owes!
    n_people = Person.all.size

    # Use a nxn array structure, in row -> column order. rows are who paid for an item, columns are the amount owed by the others to that person.
    # The diagonal will (by definition) always be zero. Implemented using a SparseArray, so that memory usage is not large
    d = SparseArray.new

    Purchase.all.each do |p|
      #As this item was paid for by p.person, they are owed the money listed in acceptances by the others (might include themselves).
      p.acceptances.each do |a|
        #If there is an acceptance from p.person to p.person, then consider this a spend of money, and don't update owednesses (you can't owe yourself)
        next if a.person == p.person

        d[p.person.id][a.person.id] = (d[p.person.id][a.person.id].nil? ? 0 : d[p.person.id][a.person.id]) + a.amount
      end
    end

    # Now, we need to simplify the resulting owednesses, so that when A owes B, and B owes A, we just need one transaction to fix this.
    # This will generate a triangular matrix
    Person.all.each do |from|
      if d.key?(from.id) then
        Person.all.each do |to|
          if d[from.id].key?(to.id) then
            #so TO owes FROM something, does FROM owe TO?
            if d.key?(to.id) && d[to.id].key?(from.id) then
              d[from.id][to.id] -= d[to.id][from.id]
              d[to.id][from.id] = 0
            end
          end
        end
      end
    end

    Owedness.delete_all

    person_books = {}

    #Iterate over the triangular form
    d.hash.each do |to, froms|
      froms.each do |from, amount|
        next if to < from

        # Store this in the caching table Owednesses
        o = Owedness.new(from_person: Person.find(from), to_person: Person.find(to), amount: amount)
        o.save!
        oi = Owedness.new(from_person: Person.find(to), to_person: Person.find(from), amount: -amount)
        oi.save!

        person_books[to] = 0 unless person_books.key? to
        person_books[from] = 0 unless person_books.key? from

        person_books[from] -= amount
        person_books[to] += amount

      end
    end

    # Calculate the minimum possible transactions to fix this
    transactions = []

    negative_people = {}
    positive_people = {}

    person_books.each do |p, balance|
      if balance < 0 then
        negative_people.store p, balance
      else
        positive_people.store p, balance
      end
    end

    positive_people.each do |to, exp|
      next if exp == 0
      negative_people.each do |from, possible|
        amt = (exp < -possible) ? exp : -possible
        transactions.push Hash[from: from, to: to, amount: amt]
        negative_people[from] -= amt
        negative_people.delete(from) if negative_people[from] == 0
      end
    end

    # Store the required transactions
    MinimalTransaction.delete_all
    transactions.each { |trans| MinimalTransaction.new(from_person: Person.find(trans[:from]), to_person: Person.find(trans[:to]), amount: trans[:amount]).save! }

    true
  end
end

app/views/purchases/_form.html.erb
<%= form_for(@purchase) do |f| %>
  <% if @purchase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@purchase.errors.count, "error") %> prohibited this purchase from being saved:</h2>

      <ul>
      <% @purchase.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_field :date %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.number_field :amount, step: 0.01, value: @purchase.amount %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, cols: 50, rows: 20 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/purchases/edit.html.erb
<h1>Editing purchase</h1>

<%= render 'form' %>

<%= link_to 'Show', @purchase %> |
<%= link_to 'Back', purchases_path %>

app/views/purchases/index.html.erb
<h1>Listing purchases</h1>

<table>
  <tr>
    <th>Date</th>
    <th>Name</th>
    <th>By</th>
    <th>Amount</th>
    <th>Description</th>
    <th>Accepted by me</th>
    <th>Accepted total</th>
    <th>Done</th>
    <th></th>
  </tr>

<% @purchases.each do |purchase| %>
  <tr>
    <td><%= purchase.date %></td>
    <td><%= purchase.name %></td>
    <td><%= purchase.person.name %></td>
    <td><%= to_money purchase.amount %></td>
    <td><%= purchase.description %></td>
    <td><%= to_money(purchase.accepted_by_me(current_person) || 0) %></td>
    <td><%= to_money purchase.accepted_total %></td>
    <td><%= check_box_tag("check#{purchase.id}", "1", purchase.accepted_total == purchase.amount, :disabled=>true) %></td>
    <td><%= link_to 'Show', purchase %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Purchase', new_purchase_path %>

app/views/purchases/new.html.erb
<h1>New purchase</h1>

<%= render 'form' %>

<%= link_to 'Back', purchases_path %>

app/views/purchases/show.html.erb
<p id="notice"><%= notice %></p>

<h3>Purchase</h3>
<p>
  <b>Date:</b>
  <%= @purchase.date %>
</p>

<p>
  <b>Name:</b>
  <%= @purchase.name %>
</p>

<p>
  <b>By:</b>
  <%= @purchase.person.name %>
</p>

<p>
  <b>Amount:</b>
  <%= to_money @purchase.amount %>
</p>

<p>
  <b>Description:</b>
  <%= @purchase.description %>
</p>

<hr />
<h3>Acceptances</h3>
<table>
  <tr>
    <th>By</th>
    <th>Amount</th>
    <th>Note</th>
  </tr>
<% @purchase.acceptances.each do |acceptance| %>
  <tr>
    <td><%= acceptance.person.name %></td>
    <td><%= to_money(acceptance.amount || 0) %></td>
    <td><%= acceptance.note %></td>
  </tr>
<% end %>
  <tr>
    <td>Total:</td>
    <td><%= to_money @purchase.accepted_total %></td>
    <td></td>
  </tr>
</table>

<h3>Change mine</h3>
<%= render partial: "acceptances/form", locals: {acceptance: @my_acceptance} %>

<hr />
<% if @purchase.person == current_person then %>
<%= link_to 'Edit', edit_purchase_path(@purchase) %> |
<% end %>

<%= link_to 'Back', purchases_path %>