config/routes.rb
EMonies::Application.routes.draw do
  devise_for :people, :controllers => { :registrations => :registrations }
  root :to => 'special#index'

  get 'summary' => 'special#summary'

  resources :people
  resources :purchases
  resources :acceptances

end

app/controllers/special_controller.rb
class SpecialController < ApplicationController
  before_action :authenticate_person!

  def index
    total = Purchase.all.size
    dealtwith = Purchase.dealtwith.size
    @num_outstanding = total - dealtwith

    respond_to do |format|
      format.html #index.html.erb
    end
  end

  def summary
    respond_to do |format|
      format.html #summary.html.erb
    end
  end
end

app/views/special/index.html.erb
<p><h1>eMonies</h1></p>
<p><h2>Hi <%= current_person.name  %></h2></p>

<p>
  <h3>Status</h3>
  <ul>
    <li><%= link_to "#{@num_outstanding} #{(@num_outstanding > 1) ? "purchase" : "purchases"} needing acceptances from you", :purchases %></li>
  </ul>
</p>

app/views/special/summary.html.erb
<h1>Summary</h1>

<p>This table shows the money (and the negative) owed from one person to another.
A positive amount indicates money is owed in that direction. Read in row then column order (to, from).
</p>

<table>
  <tr>
    <th></th>
    <th>From</th>
  </tr>

  <tr>
    <th>To</th>
    <th>\</th>
    <% Person.all.each do |from| %>
    <th><%= from.name %></th>
    <% end %>
  </tr>

  <% Person.all.each do |to| %>
  <tr>
    <th></th>
    <th><%= to.name %></th>
    <% Person.all.each do |from| %>
    <td><%= (to == from ? "~" : to_money(Owedness.owes(to, from))) %></td>
    <% end %>
  </tr>
  <% end %>
</table>

<hr />
<h2>Minimal transactions required to fix</h2>
<table>
  <tr>
    <th>To</th>
    <th>From</th>
    <th>Amount</th>
  </tr>
  <% MinimalTransaction.all.each do |trans| %>
  <tr>
    <td><%= trans.to_person.name %></td>
    <td><%= trans.from_person.name %></td>
    <td><%= to_money trans.amount %></td>
  </tr>
  <% end %>
</table>